# Generated by Django 5.1 on 2024-09-08 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_analytics', '0001_initial'),
        ('module_orders', '0004_delivery_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='module_orders.order'),
        ),
    ]
