# Generated by Django 5.1 on 2024-09-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_analytics', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregateReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Ежедневный'), ('weekly', 'Еженедельный'), ('monthly', 'Ежемесячный')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_expenses', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_orders', models.IntegerField()),
                ('total_products_sold', models.IntegerField()),
            ],
        ),
    ]
