# Generated by Django 5.1 on 2024-09-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
