# Generated by Django 5.1 on 2024-09-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_orders', '0002_alter_orderproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'Корзина'), ('ordered', 'Оформлен'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен')], default='cart', max_length=50),
        ),
    ]
