# Generated by Django 5.1 on 2024-09-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
